// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered suggestions for refining search queries for apartments.
 *
 * - refineSearchQuery - A function that takes a user's search query and returns suggestions for refining it.
 * - RefineSearchQueryInput - The input type for the refineSearchQuery function.
 * - RefineSearchQueryOutput - The return type for the refineSearchQuery function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefineSearchQueryInputSchema = z.object({
  query: z
    .string()
    .describe('The user provided query to find an apartment, can be empty.'),
  preferences: z
    .string()
    .optional()
    .describe('The user provided preferences, can be empty.'),
});
export type RefineSearchQueryInput = z.infer<typeof RefineSearchQueryInputSchema>;

const RefineSearchQueryOutputSchema = z.object({
  suggestions: z
    .array(z.string())
    .describe('An array of suggested refinements to the search query.'),
});
export type RefineSearchQueryOutput = z.infer<typeof RefineSearchQueryOutputSchema>;

export async function refineSearchQuery(input: RefineSearchQueryInput): Promise<RefineSearchQueryOutput> {
  return refineSearchQueryFlow(input);
}

const refineSearchQueryPrompt = ai.definePrompt({
  name: 'refineSearchQueryPrompt',
  input: {schema: RefineSearchQueryInputSchema},
  output: {schema: RefineSearchQueryOutputSchema},
  prompt: `You are an AI assistant designed to help users refine their search queries for apartments.

  The user is looking for an apartment, and has provided the following query:
  """{{query}}"""
  The user is also expressing the following preferences, if any:
  """{{preferences}}"""
  Suggest alternative queries that user may find more helpful and relevant to their specific goal of finding an apartment, be creative and suggest new amenities or locations. The suggestions should also include general queries without specific amenities or locations.
  Return an array of suggested refinements to the search query. Do not repeat the input query in the suggestions. Focus on suggesting new alternative options to explore.
  Format the result as a JSON object with a "suggestions" field containing an array of strings. Each string should be a suggested search query.
  Example:
  {
    "suggestions": [
      "Apartments with a gym in downtown",
      "Pet-friendly apartments near the park",
      "Luxury apartments with city view",
      "Affordable studios close to public transportation",
      "Apartments with parking"
      ]
  }
  `,
});

const refineSearchQueryFlow = ai.defineFlow(
  {
    name: 'refineSearchQueryFlow',
    inputSchema: RefineSearchQueryInputSchema,
    outputSchema: RefineSearchQueryOutputSchema,
  },
  async input => {
    const {output} = await refineSearchQueryPrompt(input);
    return output!;
  }
);
