import type { Apartment } from './types';

export const allAmenities = [
  { name: 'House Keeping', iconName: 'Sparkles' },
  { name: 'Parking', iconName: 'ParkingCircle' },
  { name: 'Laundry', iconName: 'WashingMachine' },
  { name: 'Security', iconName: 'Shield' },
  { name: 'Wifi', iconName: 'Wifi' },
];

export const apartments: Omit<Apartment, 'images' | 'host.avatar'>[] = [
  {
    id: '1',
    name: 'Sunny Downtown Loft',
    location: 'New York, NY',
    pricePerNight: 250,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    rating: 4.9,
    reviews: 120,
    description: 'A bright and spacious loft in the heart of the city. Perfect for couples looking to explore the best of New York. Enjoy stunning views and modern amenities.',
    amenities: [
      { name: 'Wifi', iconName: 'Wifi' },
      { name: 'Laundry', iconName: 'WashingMachine' },
      { name: 'Security', iconName: 'Shield' },
    ],
    imageIds: ['apt-1-1', 'apt-1-2', 'apt-1-3'],
    host: {
      name: 'Maria',
      avatarId: 'host-1',
    },
  },
  {
    id: '2',
    name: 'Nightingale Villa',
    location: 'Los Angeles, CA',
    pricePerNight: 160,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 2,
    rating: 4.95,
    reviews: 85,
    description: 'Stunning 2-bedroom mountain villa with full sea view, 5-star living, and many luxurious surroundings - First Class!',
    amenities: allAmenities,
    imageIds: ['special-offer-main', 'special-offer-thumb-1', 'special-offer-thumb-2'],
    host: {
      name: 'David',
      avatarId: 'host-2',
    },
  },
  {
    id: '3',
    name: 'Charming Garden Studio',
    location: 'Paris, France',
    pricePerNight: 180,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    rating: 4.8,
    reviews: 250,
    description: 'A cozy and charming studio with a beautiful private garden. Located in a quiet neighborhood, it\'s the perfect romantic getaway in the city of lights.',
    amenities: [
      { name: 'Wifi', iconName: 'Wifi' },
      { name: 'House Keeping', iconName: 'Sparkles' },
    ],
    imageIds: ['apt-3-1', 'apt-3-2', 'apt-3-3'],
    host: {
      name: 'Chloe',
      avatarId: 'host-3',
    },
  },
  {
    id: '4',
    name: 'The Penthouse Suite',
    location: 'Miami, FL',
    pricePerNight: 600,
    guests: 6,
    bedrooms: 3,
    beds: 3,
    baths: 3,
    rating: 5.0,
    reviews: 45,
    description: 'Unparalleled luxury in this stunning penthouse. With three bedrooms, a gourmet kitchen, and a wrap-around balcony, this is the ultimate Miami experience.',
    amenities: allAmenities,
    imageIds: ['apt-4-1', 'apt-4-2', 'apt-4-3'],
    host: {
      name: 'Alex',
      avatarId: 'host-4',
    },
  },
];
